[RAISETECH-57] フロント／バックエンドの連携確認作業
RaiseTech-team01/reservation_app pull request #51
Opened 2021-04-20 07:04 UTC by yukinkomob

## 概要
- Vue.js の機能を利用して "Hello Vue" が表示可能な状態にした

## タスク内容
- webpacker:install / compile を実行
- webpacker:install:vue を実行
- rails generate controller home top を実行
  - これはサンプルとしてのコントローラ（将来的には削除予定）
- routes.rb の更新
- app/views/home/top.html.erb にて "Hello Vue" (Vue の機能を利用した文字列出力）が行われるようにした

## その他参考情報
- http://localhost:3000/home/top にアクセスすると、"Hello Vue" が表示される

2021-04-20 07:04 UTC, yukinkomob commented
レビューをお願いいたします。

2021-04-20 07:06 UTC, yukinkomob commented
@KazusaNakagawa さん

そういえば、今回の対応をした時は、MissingEntryError は起きませんでした。
rails:webpacker:install 実行時に、webpacker.yml のコンフリクトが発生して、新しいファイルで上書きしたのですが、それが良かったのかも知れません。（正確な原因は未特定ですが、これまでの作業との差分はそれくらい）
（それまでは手動でマージしたりしていました）

2021-04-20 16:54 UTC, KazusaNakagawa commented
> webpacker.yml のコンフリクトが発生して、新しいファイルで上書きした

確かに上書きするか、選択ありましたね!
自分も **yes** で対応してたかと。なんでだろ🤔

2021-04-20 17:17 UTC, KazusaNakagawa commented
> > webpacker.yml のコンフリクトが発生して、新しいファイルで上書きした
> 
> 確かに上書きするか、選択ありましたね!
> 自分も **yes** で対応してたかと。なんでだろ🤔

2021-04-20 17:23 UTC, KazusaNakagawa commented on rails_app/config/routes.rb
> +  get "home/top" => "home#top"
ここは、**get** でいけたんですね!

2021-04-20 17:26 UTC, KazusaNakagawa approved these changes
連携確認ありがとうございます🙏
これで実装進る事ができればですね!!

2021-04-23 08:16 UTC, TOBE-ASUNARO approved these changes
確認しました。ありがとうございます。

本件と直接関係ありませんが、DBのversionが、10.5.9となっています。
2021/04/23現在は、修正のうえ表示されました。

docker-compose.yml
...
services:
  db:
    image: mariadb:10.5.9
...

2021-04-23 08:21 UTC, yukinkomob commented
@TOBE-ASUNARO 

> 本件と直接関係ありませんが、DBのversionが、10.5.9となっています。
> 2021/04/23現在は、修正のうえ表示されました。

ご確認ありがとうございます。mainブランチでは修正した値（10.5.9）が適用されているということですかね。
こちらではDBのversionは修正していないのでコンフリクトは発生しておらず、適用に関しては問題ないかと考えています。

2021-04-24 16:26 UTC, yukinkomob commented
@TOBE-ASUNARO 

自分の確認も兼ねて rebase してみました。
rebase する場合ですが、`git push --force` として force オプションを付与する必要があると思いますので、ご注意ください。
（自分が修正した以外のコミットを操作する破壊的な操作になるので、通常の利用方法だと安全面からpushを拒絶されます。--force オプションを付けることで、そのリスクについては許容済みであるという確認が取れたものとして、rebase が実行されます）

2021-04-25 05:07 UTC, FURUYANAOKI0803 requested changes
すみません。遅くなりました。確認いたしました。

2021-04-25 05:07 UTC, FURUYANAOKI0803 approved these changes

2021-04-25 05:17 UTC, yukinkomob commented
レビューありがとうございました。

2021-04-25 05:19 UTC, merged

2021-04-25 06:08 UTC, yukinkomob commented
test